# Code challenge, proving matrix multiplication with Layer perspective

Method: 

|a c| * |1 2| = |a*1  a*2| + |c*3  c*4| = |a+3c  2a+4c|

|b d|   |3 4|   |b*1  b*2|   |d*3  d*4|   |b+3d  2b+4d|

The method is slightly different from the traditional dot-product collection.
(See the link as example)
https://cdn.kastatic.org/googleusercontent/rk4fR1jNJsGUfdHOc87UzuQh2zokwYDoVo3Hk1m3s6ToGDgW6KxgrsUeIj8-CJeV6cNf6WB8B6sRHt3BoGBdVY7h

In [1]:
import numpy as np
import pandas as pd

Matrix1 = np.random.randint(100, size=(4, 4))
Matrix2 = np.random.randint(100, size=(4, 4))

#use a for loop to multiply the matrices element by element and then compare against the built-in method
print(Matrix1)
print("...")
print(Matrix2)
print("...")



[[67 56 15 63]
 [41 23 50 62]
 [ 8 29 78 36]
 [66  8 98 73]]
...
[[33 99 12 14]
 [68 82 55 70]
 [85 30 80 61]
 [ 2 15 78 74]]
...


In [19]:
#Slicing rows and columns

vc = Matrix1[:, 0].reshape(4,1)
print(vc)
print(Matrix2[0])



[[67]
 [41]
 [ 8]
 [66]]
[33 99 12 14]


In [32]:
#Creating and summing the layers the layers

m1Xm2 = np.zeros(4)
for i in range(4):
    layer = Matrix1[:, i].reshape(4,1)*Matrix2[i]
    m1Xm2  = m1Xm2+layer
    #print(layer)
print(m1Xm2)

[[ 7420. 12620.  9998. 10435.]
 [ 7291.  8375. 10593.  9822.]
 [ 8938.  6050. 10739.  9564.]
 [11198. 11225. 14766. 12864.]]


In [30]:
#Proving against the built-in method
np.dot(Matrix1,Matrix2)

array([[ 7420, 12620,  9998, 10435],
       [ 7291,  8375, 10593,  9822],
       [ 8938,  6050, 10739,  9564],
       [11198, 11225, 14766, 12864]])

In [ ]:
#The matrix is the same. 