In [12]:
#Probando el concepto broadcasting matrix

import numpy as np
import pandas as pd
a = np.reshape(np.arange(1,13),(3,4),"C")
b = np.arange(1,5)
c = np.array([[1],[2],[3]])
print(a+c)
print(c)

[[ 2  3  4  5]
 [ 7  8  9 10]
 [12 13 14 15]]
[[1]
 [2]
 [3]]
