# Dot product permutations
Create 2 matrices 4x6, fill them with random numbers and compute the dot product between all the columns.

In [2]:
import numpy as np
import pandas as pd

Matrix1 = np.random.randint(100, size=(4, 6))
Matrix2 = np.random.randint(100, size=(4, 6))

#define the matrix that will store the results.
Results_matrix = []
Headers = ["Column Matrix1","Column Matrix2","Dot product"]

print("This is the Matrix 1")
print(Matrix1)
print("-"*22)
print("This is the Matrix 2")
print(Matrix2)

This is the Matrix 1
[[12 42 20 12 97 64]
 [19 20 95 39 78 97]
 [ 1 96 68  4 67 16]
 [ 6 53 74 70 89 30]]
----------------------
This is the Matrix 2
[[75 59 67 19  7 53]
 [73 81 49 41 26 12]
 [13 99 42 73 45 94]
 [20 13 18 31 81 85]]


In [57]:
for i in range(6):
    for j in range(6):
        vector = [i,j,np.dot(Matrix1[:,i],Matrix2[:,j])]
        Results_matrix.append(vector)

#Data frame printing
df = pd.DataFrame(data=Results_matrix,
                columns = Headers)
print(df)

    Column Matrix1  Column Matrix2  Dot product
0                0               0        14382
1                0               1         5233
2                0               2        15398
3                0               3         9083
4                0               4         7080
5                0               5        14804
6                1               0        17826
7                1               1        10021
8                1               2        17228
9                1               3         8087
10               1               4        11349
11               1               5        14906
12               2               0        21052
13               2               1         8415
14               2               2        22002
15               2               3        15566
16               2               4        10644
17               2               5        20943
18               3               0        14654
19               3               1      