In [3]:
import numpy as np
import pandas as pd

In [46]:
size = 99
Matrix1 = np.random.randint(100, size=(size, size))
minors_matrix = np.eye(size)

cofactors_matrix = np.empty([size, size])
unos = -1
print(Matrix1)
determinant = np.linalg.det(Matrix1)
if determinant == 0:
    print("Matrix has no inverse")
else:
    for i in range(size):
        for j in range(size):
            unos = unos*(-1)            
            cofactors_matrix[i][j] = unos
            
            temporary = np.delete(Matrix1, i, 0)
            temporary = np.delete(temporary, j, 1)
            minors_matrix[i][j] = np.linalg.det(temporary)

print(minors_matrix , cofactors_matrix)
H = np.multiply(minors_matrix,cofactors_matrix) 
inverse_matrix = H.T * (determinant**-1)
print(inverse_matrix)

[[78 78 30 ... 99 53 10]
 [42  3 55 ... 22 29 84]
 [87 37 22 ...  8 47 11]
 ...
 [87 28 74 ... 83 45 38]
 [43 86 57 ... 68 54 65]
 [98 21 39 ...  9 16 77]]
[[ 1.29509018e+220 -1.64099389e+218 -4.04425011e+219 ... -5.90048255e+218
   7.86730429e+218 -1.09883606e+220]
 [ 1.66711785e+220  4.53448447e+220 -1.90556226e+220 ... -2.93557625e+220
  -2.53756790e+220  4.86488175e+219]
 [ 2.18202989e+219  3.01606808e+219  1.28065651e+220 ...  6.37482130e+219
   1.06563421e+220  5.87259737e+219]
 ...
 [-1.57368457e+220 -2.63889155e+220  1.32746873e+220 ...  2.68850719e+220
   1.02117650e+220  1.63967281e+220]
 [ 7.40942579e+219 -1.06106014e+220 -1.01074986e+219 ...  2.83602034e+218
   5.48768562e+219 -2.91063372e+219]
 [-5.67754919e+219 -3.66274327e+220 -3.82664131e+218 ...  7.90095642e+219
   9.16814222e+219 -2.71143953e+220]] [[ 1. -1.  1. ...  1. -1.  1.]
 [-1.  1. -1. ... -1.  1. -1.]
 [ 1. -1.  1. ...  1. -1.  1.]
 ...
 [ 1. -1.  1. ...  1. -1.  1.]
 [-1.  1. -1. ... -1.  1. -1.]
 [ 1. -1.  1

In [47]:
np.linalg.inv(Matrix1)

array([[ 3.35940325e-03, -4.32442561e-03,  5.66008332e-04, ...,
        -4.08206406e-03, -1.92197034e-03, -1.47272966e-03],
       [ 4.25666127e-05,  1.17622403e-02, -7.82353930e-04, ...,
         6.84516105e-03, -2.75234030e-03,  9.50098446e-03],
       [-1.04905953e-03,  4.94293924e-03,  3.32196299e-03, ...,
         3.44339170e-03,  2.62183780e-04, -9.92612828e-05],
       ...,
       [-1.53055753e-04,  7.61474727e-03,  1.65359878e-03, ...,
         6.97386171e-03, -7.35650392e-05,  2.04947108e-03],
       [-2.04074188e-04, -6.58233226e-03, -2.76420521e-03, ...,
        -2.64888401e-03,  1.42347994e-03, -2.37817314e-03],
       [-2.85032927e-03, -1.26192754e-03,  1.52332425e-03, ...,
         4.25323446e-03,  7.55004752e-04, -7.03334711e-03]])