In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [18]:
#step 1, defining matrix size
rows = 3
columns = 3



matrix = np.random.randint(100, size=(rows, columns))
print(matrix)

[[13 61 96]
 [53 89 29]
 [75 82 82]]


In [21]:
#Step get the GS Matrix associated to the defined.

Q,R = np.linalg.qr(matrix)

In [22]:
matrix_2 = Q@R

print(matrix_2)

[[13. 61. 96.]
 [53. 89. 29.]
 [75. 82. 82.]]


In [23]:
r = matrix.T@Q
print(r)
print(R)

[[-9.27523585e+01  3.24185123e-14  1.36557432e-14]
 [-1.25711089e+02  5.06233353e+01 -1.55431223e-15]
 [-9.63317823e+01  6.02691766e+01  6.21997916e+01]]
[[ -92.75235846 -125.71108911  -96.33178227]
 [   0.           50.62333527   60.26917663]
 [   0.            0.           62.19979159]]
